### ISSUE TITLE
version not supported

### ISSUE THREAD

**Issue by oddbenk** [Xyr0s1gn/Taurus-vscode-theme#1]
Hi!

I'm running code-oss version 1.29 on a raspberry pi4.
Unfortunetly the newest version have some display issues while launching the oss-code.
I want to use your theme but on version 1.29 it's not supported.
Can you maybe create one with this version support?

**Comment by misterklaes** [comment]
Added. Have fun)

**Comment by oddbenk** [comment]
thank you very much man!
